site_name: "cp2k-basis"
site_description: "Parser for CP2K basis sets and GTH pseudopotentials, and a webserver to find matching basis and pseudo for your calculations."
site_url: "https://pierre-24.github.io/cp2k-basis/"
repo_url: "https://github.com/pierre-24/cp2k-basis"
edit_uri: "blob/dev/docs/"
repo_name: "pierre-24/cp2k-basis"

nav:
    - Home: index.md
    - About: about.md
    - For the users:
          - On basis sets and GTH pseudopotentials in CP2K: users/basis_sets_and_pseudos.md
          - How to use the web interface?: users/webserver.md
          - REST API reference: users/api.md
    - For the developers:
          - Install and contribute: developers/install.md
          - Build, use and improve the library: developers/library_build.md
          - Basis sets and pseudopotentials files format in CP2K: developers/bs_and_pseudo_file_format.md
          - Library file format: developers/library_file_format.md

theme:
  name: material

markdown_extensions:
    - admonition
    - pymdownx.details
    - pymdownx.arithmatex:
        generic: true
    - pymdownx.highlight
    - pymdownx.superfences
    - pymdownx.snippets:
        check_paths: true
    - toc:
        permalink: "¤"

plugins:
    - search
    - mkdocstrings

extra_css:
  - https://cdn.jsdelivr.net/npm/katex@0.16.4/dist/katex.min.css

extra_javascript:
  - https://cdn.jsdelivr.net/npm/katex@0.16.4/dist/katex.min.js
  - do-katex.js